---
Name: mainsite
After: 'framework/*','cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SiteVersion:
  version: 1.0
SSViewer:
  theme: 'default'
Page:
  sectionIDs:
    'carousel': 'Carousel'
    'ciders': 'Ciders'
    'story': 'Story'
    'sustainability': 'Sustainability'
    'awards': 'Awards'
    'team': 'Team members'
    'contact': 'Contact'
    'buy': 'Buy now'
    'news': 'News & Blog'
    'subscription': 'Subscription form'
  extensions:
    - OpenGraphExtension
    - TwitterCardExtension
    - SeoObjectExtension
    - SEOExtension
SiteConfig:
  extensions:
    - CustomSiteConfig
    - OpenGraphExtension
    - TwitterCardExtension
Page_Controller:
  extensions:
    - PageControllerDecorator
ModelAdmin:
  extensions:
    - ModelAdminExtension

SeoConfig:
    Page: true
    ErrorPage: false
    RedirectorPage: false
    VirtualPage: false
i18n:
  all_locales:
    zh_Hans: Chinese (Simplified)
  common_locales:
    zh_Hans:
      name: Chinese (Simplified)
      native: 简体中文
Link:
  extensions:
    - LinkExtension
    - SortOrderExtension
DataList:
  extensions:
    - DataListExt

ArrayList:
  extensions:
    - DataListExt

HtmlEditorField:
  insert_width: 1344

SocialMediaLink:
  SocialMedias:
    'facebook': 'Facebook'
    'twitter': 'Twitter'
    'linkedin': 'LinkedIn'
    'google-plus': 'G+'
    'skype': 'Skype'
    'instagram': 'Instagram'
    'whatsapp': 'Whatsapp'
    'qq': 'QQ'
    'envelope-o': 'Email'
    'weixin': 'WeChat'
    'weibo': 'Weibo'
    'newspaper-o': 'Newsletter'
GoogleAPIs:
  Map: 'AIzaSyB5LdVLLklbFKZ29l7kSL4PW_J46c2apPI'

Cider:
  colours:
    red: 'Red apple'
    crisp: 'Crisp apple'
    hopped: 'Hopped'
    ginger: 'Ginger beer'
    'two-point-five': 'Two point five'
    crumble: 'Apple crumble'
  labels:
    'en_NZ':
      'see': 'See',
      'smell': 'Smell',
      'taste': 'Taste',
      'trywith': 'Try me with',
      'dryness': 'Dryness',
      'tannin': 'Tannin',
      'avail': 'Available in'
    'zh_Hans':
      'see': '视觉'
      'smell': '嗅觉'
      'taste': '味觉'
      'trywith': '佐餐推荐'
      'dryness': '甜度'
      'tannin': '单宁含量'
      'avail': '容量'
